---
- name: Installation of coding tools
  hosts: localhost

  tasks:
    - name: Install pipx
      become: yes
      package:
        name: pipx
        state: present

    - name: config pipx
      become: yes
      shell: pipx ensurepath

    - name: Install poetry
      become: no
      community.general.pipx:
        name: poetry
        state: present
        install_deps: true

    - name: Install mypy
      become: no
      community.general.pipx:
        name: mypy
        state: present
        install_deps: true

    - name: Install Podman
      become: yes
      package:
        name: podman
        state: present

    - name: Install podman-compose
      become: yes
      package:
        name: podman-compose
        state: present

    - name: Clone Pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv